### ISSUE TITLE
Overwrite not working

### ISSUE THREAD

**Issue by BeeVirtual** [SnowdogApps/magento2-menu#120]
Hello. 
I tried this in Magento 2.4.0 using php7.4

Install version Support2.4.0
Declare menu in admin with identifier "menu_hamburger"
Create a Snowdog_Menu folder in app/design/theme
Insert folder menu_hamburger with same structure as default phtml templates
Result - Magento is still displaying default phtml files and ignoring overwrite.

**Comment by snowremi** [comment]
Hi @BeeVirtual, thank you for submitting the issue. I created an internal ticket DEV-70293 for that, and we'll work on this shortly

**Comment by jochhop** [comment]
Hi @BeeVirtual we have been investigating the issue, but unfortunately we cannot replicate it. We have done the following tests:

- Used Magento 2.4 version (clear installation)
- Create a menu with active nodes and code: `menu_hamburger`
- Create a theme under: `app/design/frontend/Snowdog/xyz`
- Override menu templates within such theme, under: `app/design/frontend/Snowdog/xyz/Snowdog_Menu/templates/menu_hamburger/menu/node_type`

Then, the overriden template is used instead of the original template.

Per your original description, we can see the following:

> Create a Snowdog_Menu folder in app/design/theme

so maybe the path `app/design/theme` is not correct? (it should be `app/design/frontend/CustomTheme`

**Comment by snowremi** [comment]
@BeeVirtual please verify the answer above and let us know if changing the path solved your issue. Otherwise, please provide more details on how to replicate the error. Thank you

**Comment by snowremi** [comment]
I'm closing this issue. We couldn't replicate the error, and we couldn't retrieve any more details
