### ISSUE TITLE
Removing duplicate image removes image for all nodes

### ISSUE THREAD

**Issue by template-provider** [SnowdogApps/magento2-menu#192]
I have a node (custom url) and upload an image 123.jpg.
I add a second node (category) and upload the same image 123.jpg (same level as before)

I remove the image from the custom url node.

Result:
The image is removed from the server, but it is still linked in the second node.

**Comment by andrzejborkowski** [comment]
@template-provider Hi, could you please provide more details since I can't replicate the issue? What is the expected result? What do you mean under "it is still linked in the second node"?

**Comment by Igloczek** [comment]
@andrzejborkowski I think we can send it to our devs, we just assumed that every image is in use just once, so if you remove it from one node, it's gone from the disc, but other nodes still keep referencing it.

**Comment by template-provider** [comment]
@Igloczek exaclty ... thx for clearing it up

**Comment by andrzejborkowski** [comment]
thanks, I created internal ticket DEV-80414, we'll start working on it soon

**Comment by akai-z** [comment]
Actually, the way node images upload feature was implemented was by making each node have its own unique image.  
So if we add image `123.jpg` to one node, and then add the same image to another node,  
then the image name for the other node will be `123_1.jpg` (and then `123_2.jpg` and so on).  
This was done using the node image file upload auto rename feature, which its implementation can be found [here](https://github.com/SnowdogApps/magento2-menu/blob/2.15.0/Model/Menu/Node/Image/File.php#L58).

In my opinion,  
removing an image from one node must not remove the same image from all other nodes (including other menus' nodes).  
(i.e. A user might want to remove an image from one node, but still keep using the same image in other nodes.)  
That's why image upload auto rename feature was enabled, in order to not break other nodes with their images.  
And the same case applies to Magento catalog products, for example.

With that being said,  
there are actually some bugs related to node image upload at the moment (can be mostly found in `develop` branch),  
where if we create a new node without an image while there is another node with an image,  
then the new node will copy (link to) the other node image.  
And another issue is that if we upload an image to a node, it might check the current image from another node.  
Also, the image upload auto rename feature does not seem to function properly at the moment.

Those issues are somewhat related to this discussion.
We currently have another internal ticket for them (`DEV-79674`).

**Comment by andrzejborkowski** [comment]
@template-provider after some of our internal discussions we decided to leave current functionality as is - each menu node should have its own unique image file (details provided in the previous comment). Anyway, thanks a lot for your suggestion!
