### ISSUE TITLE
No css and not working well in frontend

### ISSUE THREAD

**Issue by tartreau** [SnowdogApps/magento2-menu#57]
Hello, I just installed your extension on my website. I see my menu in my backend.
But the menu isn't display in my frontend. I've copied and pasted your code (with the same identifier for the menu). The menu is appearing without any css in the page, it's only display outside store.menu. 

I.E : I can display in page.wrapper, I've menu and submenu but no css and not in the right place

And I have this error in my console : /fr_FR/images/icon-sprite.svg 404 (Not Found) (I have a custom theme)

**Comment by Igloczek** [comment]
We are shipping this module without styles, so it's expected behavior.

SVG icons are indeed missing and it's our fault, but we designed this module to be used with [Alpaca theme](https://github.com/SnowdogApps/magento2-alpaca-theme) which provide both styling and icons.

So if you want to use this module, without our theme, you need to custmize templates and add own styles to fit your project needs.

**Comment by rav-redchamps** [comment]
@tartreau If you are looking for support on Luma or Luma based themes then you may try this https://github.com/redchamps/snowdog-menu-luma-support we added Luma classes to the menu

**Comment by Igloczek** [comment]
@rav-redchamps thanks for this extension! I've added link to it in the description.

**Comment by vseager** [comment]
@Igloczek I have just published a nice lightweight module which seamlessly integrations Snowdog menu with Luma:

https://github.com/vseager/magento2-snowdog-menu-luma

It injects the nodes using core functionality so has no custom templates. As a result, it works faultlessly with Luma's core templates. Please take a look and if you think it will benefit the community then I would be more than happy for you to link to it from your README as another solution for Luma.
